// src/hooks/self-improving.ts
/**
 * Self-Improving Agent Hooks for MantisBot
 *
 * 集成 self-improving-agent skill，实现：
 * 1. 错误检测 - 当工具调用失败时提醒记录
 * 2. 学习提醒 - 对话结束时提醒记录学习
 * 3. 学习日志管理 - 读写 .learnings 目录
 */

import { appendFile, mkdir, readFile, writeFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type { HookContext, HookHandler, HookEvent } from './loader.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '../../');
const LEARNINGS_DIR = join(PROJECT_ROOT, '.learnings');

// 学习日志文件
const LEARNING_FILES = {
  errors: join(LEARNINGS_DIR, 'ERRORS.md'),
  learnings: join(LEARNINGS_DIR, 'LEARNINGS.md'),
  features: join(LEARNINGS_DIR, 'FEATURE_REQUESTS.md'),
} as const;

// 错误模式检测（参考 self-improving-agent/scripts/error-detector.sh）
const ERROR_PATTERNS = [
  /error:/i,
  /failed:/i,
  /exception:/i,
  /fatal:/i,
  /ECONNREFUSED/,
  /ENOENT/,
  /EPERM/,
  /ETIMEDOUT/,
  /command not found/i,
  /permission denied/i,
  /no such file/i,
  /unexpected token/i,
  /syntax error/i,
];

// 学习条目模板
interface LearningEntry {
  type: 'error' | 'learning' | 'feature';
  category?: string;
  timestamp: string;
  content: string;
  context?: string;
}

/**
 * 确保学习日志目录存在
 */
export async function ensureLearningsDir(): Promise<void> {
  if (!existsSync(LEARNINGS_DIR)) {
    await mkdir(LEARNINGS_DIR, { recursive: true });
  }
  for (const file of Object.values(LEARNING_FILES)) {
    if (!existsSync(file)) {
      await writeFile(file, `# ${file.split('/').pop()}\n\n> Auto-generated by self-improving-agent\n\n`);
    }
  }
}

/**
 * 追加学习条目到对应文件
 */
async function appendLearning(entry: LearningEntry): Promise<void> {
  await ensureLearningsDir();

  const filePath = entry.type === 'error'
    ? LEARNING_FILES.errors
    : entry.type === 'feature'
      ? LEARNING_FILES.features
      : LEARNING_FILES.learnings;

  const categoryTag = entry.category ? `[${entry.category}]` : '';
  const contextSection = entry.context ? `\n**Context:** ${entry.context}` : '';

  const markdown = `
---

## ${entry.timestamp} ${categoryTag}

${entry.content}${contextSection}

`;

  await appendFile(filePath, markdown);
  console.log(`[SelfImproving] Logged ${entry.type} to ${filePath.split('/').pop()}`);
}

/**
 * 检测工具结果中是否包含错误
 */
function detectError(result: unknown): { hasError: boolean; errorMessage?: string } {
  if (!result) return { hasError: false };

  const resultStr = typeof result === 'string'
    ? result
    : JSON.stringify(result);

  for (const pattern of ERROR_PATTERNS) {
    const match = resultStr.match(pattern);
    if (match) {
      return {
        hasError: true,
        errorMessage: match[0],
      };
    }
  }

  // 检查 isError 标志
  if (typeof result === 'object' && result !== null && 'isError' in result) {
    return { hasError: (result as { isError: boolean }).isError, errorMessage: 'Tool reported error' };
  }

  return { hasError: false };
}

/**
 * 工具调用后 Hook - 检测错误并提醒
 */
export const toolCalledHandler: HookHandler = async (context: HookContext) => {
  const { data } = context;
  const { tool, result, isError } = data as {
    tool?: string;
    result?: unknown;
    isError?: boolean;
  };

  if (!tool) return;

  const errorCheck = detectError(result);
  if (isError || errorCheck.hasError) {
    console.log(`[SelfImproving] ⚠️ Error detected in tool: ${tool}`);
    console.log(`[SelfImproving] Consider logging this error to .learnings/ERRORS.md`);

    // 可以在这里触发提醒，或者直接记录
    // 目前只打印日志，避免自动记录可能敏感的信息
  }
};

/**
 * Agent 结束 Hook - 提醒记录学习
 */
export const agentEndHandler: HookHandler = async (context: HookContext) => {
  const { data } = context;
  const { success, toolCalls } = data as {
    success?: boolean;
    toolCalls?: Array<{ tool: string; result: unknown }>;
  };

  // 统计本次对话的工具调用
  const toolCount = toolCalls?.length || 0;
  const errorCount = toolCalls?.filter(tc => detectError(tc.result).hasError).length || 0;

  if (errorCount > 0) {
    console.log(`[SelfImproving] 📝 Session completed with ${errorCount} error(s) out of ${toolCount} tool calls.`);
    console.log(`[SelfImproving] Consider reviewing and logging learnings to .learnings/`);
  }
};

/**
 * 记录学习（供外部调用）
 */
export async function logLearning(
  type: 'error' | 'learning' | 'feature',
  content: string,
  options?: { category?: string; context?: string }
): Promise<void> {
  await appendLearning({
    type,
    category: options?.category,
    timestamp: new Date().toISOString(),
    content,
    context: options?.context,
  });
}

/**
 * 读取学习日志
 */
export async function readLearnings(type: 'errors' | 'learnings' | 'features'): Promise<string> {
  const filePath = LEARNING_FILES[type];
  if (!existsSync(filePath)) {
    return `No ${type} logged yet.`;
  }
  return readFile(filePath, 'utf-8');
}

/**
 * 注册所有 self-improving hooks
 */
export function registerSelfImprovingHooks(
  register: (event: HookEvent, handler: HookHandler) => void
): void {
  register('tool.called', toolCalledHandler);
  register('agent.end', agentEndHandler);
  console.log('[SelfImproving] Hooks registered: tool.called, agent.end');
}

// 导出便捷方法
export const selfImproving = {
  logLearning,
  readLearnings,
  registerHooks: registerSelfImprovingHooks,
};
